[package]
name = "FOMOSv3-Blue"
version = "0.1.0"
authors = ["NathanMcMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.12"

[dependencies]
novusk = { git = "https://github.com/NathanMcMillan54/novusk" }
