[package]
name = "FOMOSv3-Blue"
version = "3.0.0"
authors = ["NathanMcMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.18"

[dependencies.novusk]
git = "https://github.com/NathanMcMillan54/novusk"
tag = "v3-beta-a3.2.1"
features = ["bios_boot", "us_keyboard", "rpi3"]
